### ISSUE TITLE
Set allowed maximum file size upload limit

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-fileexplorer#118]
If a user tries to upload a file greater than some max file size (e.g., 100 MB) then stop the user and display a helpful message with a link to OSC's help page for [SFTP](https://www.osc.edu/supercomputing/getting-started/getting-connected) or the link for [Globus Connect](https://www.osc.edu/documentation/howto/transfer_files_using_globus_connect).

More discussion is necessary for this. Possible complications can be due to Chrome's ability to upload an entire directory.

Note: This may not be necessary if we scrap the current FileExplorer for a new app altogether.

**Comment by brianmcmichael** [comment]
Here's the discussion of the hardware component of this for reference.
https://github.com/OSC/ood-fileexplorer/issues/2
