### ISSUE TITLE
Safari: SyntaxError: Unexpected use of reserved word 'let' in strict mode

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-fileexplorer#122]
Javascript keyword "let" is not compatible with Safari. Not sure if this was preexisting or introduced by the switch to the unminified smalltalk.js.

<img width="1148" alt="screen shot 2016-09-08 at 11 58 33 am" src="https://cloud.githubusercontent.com/assets/2374718/18356675/b1561222-75bb-11e6-865e-7d2004e6c13e.png">

Unsupported in any version of Safari. May be able to fix it by just using a simple assignment.
http://caniuse.com/#search=let

**Comment by ericfranz** [comment]
Fixed in ed5d8bb3459d4b280c137e99e493279030f58f7a

**Comment by brianmcmichael** [comment]
Fixed.
