### ISSUE TITLE
Replace old Fontello icons with newer version, or a different source for IE11 compatibility.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-fileexplorer#124]
The Fontello icons used in File Explorer were generated some time ago and do not work with IE11.

This is a known issue at https://github.com/fontello/fontello/issues/467

There have been several changes more recently to Fontello with address the IE changes.

https://github.com/fontello/svg2ttf/blob/master/CHANGELOG.md#300--2016-02-12

We should update to a new version of Fontello fonts, or find suitable font-awesome or glyphicon replacements.

**Comment by ericfranz** [comment]
If we do this, will we be able to add back support for IE11? How expensive is this change?

**Comment by ericfranz** [comment]
@brianmcmichael please estimate the cost of this with a short technical design - what steps will be taken. what code will be modified?

**Comment by brianmcmichael** [comment]
Replacing the existing fontello icons would be the most difficult since the result is compiled from several sources. This is compounded by the fact that the original developer used some custom icons in sourcing these.

The existing icon config file is here: https://github.com/OSC/cloudcmd/blob/osc-5.3.1/font/fontello.json

Many of these existing fonts are already "font-awesome" fonts, so I propose that we just link in the "font-awesome" library, and update the original html tags to point to the counterparts in the font-awesome library, choosing suitable replacements from that catalog.

Font imports are currently configured in https://github.com/OSC/cloudcmd/blob/osc-5.3.1/css/urls.css and set to tags at https://github.com/OSC/cloudcmd/blob/osc-5.3.1/css/icons.css

**Comment by ericfranz** [comment]
Are the only uses of those icons on static buttons in our interface? If so, then the change would take an hour to fix and test?

**Comment by brianmcmichael** [comment]
I don't know if they are used in any of the existing submenus. I think we've stripped out most of the other places these are used. So I don't think so, and I've used this enough that I'd probably remember if it did.

Yeah, maybe an uninterrupted hour.

**Comment by ericfranz** [comment]
@bgohar I recommend we fix this immediately as we could then verify and update the browser requirements so IE11+ becomes supported (as long as IE11 works with everything else, which it should)

**Comment by ericfranz** [comment]
@brianmcmichael we can go ahead and do this

**Comment by brianmcmichael** [comment]
I experimented with this a little the other day. Adding Font Awesome did not actually fix the problem.

- Open a new inPrivate window in IE11 and load File Explorer. Icons appear.
- Reload page
- Icons disappear

This appears to actually be related to https://github.com/FortAwesome/Font-Awesome/issues/7681

By removing `no-store` from the header at https://github.com/OSC/ood-fileexplorer/blob/master/app.js#L31 the problem will probably be corrected in IE11 with the existing font set.

**Comment by ericfranz** [comment]
It seems our cache invalidation should still work by removing `no-store` but we should verify that with this change.

**Comment by brianmcmichael** [comment]
Fixed by https://github.com/OSC/ood-fileexplorer/pull/125
