### ISSUE TITLE
Large passenger downloads are filling up /tmp

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-fileexplorer#126]
Report from systems that `/tmp` was filling up on `webdev02`
[INC0307858](https://oarnet.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=47fe5c3cdbde62004a8a7d3ebf9619ac%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true)

Analysis revealed a user attempting to download a 10GB file in the file explorer app was causing the `/tmp` dir to fill. Currently `/tmp` only has about 8.5GB space free on a 10GB mount.

This appears to be an issue with Passenger 4.0 buffering data to memory, and then to disk if the file is too large. It can be corrected by an upgrade to Passenger 5.0, which is not viable currently because it is not in the Software Collections library.

As a workaround, the plan is the create a new infrastructure route which will allow for direct downloads through the NGINX server. See https://github.com/OSC/nginx_stage/issues/10

Once the new route is in place, `ood-fileexplorer` will need to be updated to utilize the infrastructure path for file download requests. (Currently planned at `pun/files/<path>/<to>/<file>`)

**Comment by brianmcmichael** [comment]
**Update**

New route is in place. Path spec is:

`pun/download/<path>`

**Comment by ericfranz** [comment]
In the .env file we probably should put a download path env var with the default value (when the env is not provided) being the internal api of the app.

**Comment by brianmcmichael** [comment]
done, along with modifications to nginx stage, in `v1.2.0`
