### ISSUE TITLE
Error when using "Go To" on a file

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-fileexplorer#128]
https://github.com/OSC/ondemand-testing/issues/25#issuecomment-228834157

> Click Go to. Type the path to a file that exists (not a directory), and press enter. File explorer becomes unusable.
> 
> Instead, error should display saying you can only type in directories.

![](https://cloud.githubusercontent.com/assets/512333/16391185/0346cf1c-3c74-11e6-933c-3628f1c0fadd.png)

**Comment by brianmcmichael** [comment]
Fixed at https://github.com/OSC/cloudcmd/commit/c2dac79f4499adf2f8c6a98252dc59ac7b22d04e

Removes the bug that makes cloudcmd unusable when user uses "Go To" on a directory and adds an error message that the user must select a directory.

**Comment by ericfranz** [comment]
If pressing okay, either just close both dialogs or reopen Go To dialog with the text the user typed in, but do not navigate to /.

**Comment by ericfranz** [comment]
This https://github.com/OSC/cloudcmd/blob/335cff7331a907c3ebe2706c8095cd20b912c9d9/lib/cloudfunc.js#L151-L173 is actually correct - in that its a guard clause to recover from edge cases.

Ignore previous comment. We'll readdress when doing File Explorer 2.0
