### ISSUE TITLE
Drag folder from window to desktop does not work.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-fileexplorer#129]
In Chrome, select a folder and drag it to the desktop.

Chrom errors with "Failed - No file" after attempting to download `<foldername>.tar.gz`

This functionality is attempting to use the old `/pack` api, which we've modified with a custom middleware.

Ideally, app should send a `.zip` file to the desktop in the same way that clicking 'Download' button zips a folder, preferably using the same route as the "download" option.

**Comment by ericfranz** [comment]
Is this preexisting or was this introduced by recent changes?

**Comment by brianmcmichael** [comment]
This was probably introduced when we added the zipping functionality at 

https://github.com/OSC/cloudcmd/commit/a82961696f87ae880370d11e459188f5524d7afb

and

https://github.com/OSC/ood-fileexplorer/commit/b95330643c17580e0106f11fa49bd51f8c7c1a37

It's not an advertised feature, or one that we commonly test for, however, so I just noticed it.

**Comment by brianmcmichael** [comment]
fixed at https://github.com/OSC/cloudcmd/commit/07c6c366a4e22ec760e5742d3ade8cbce2913f0d

Will be deployed in next release.
