### ISSUE TITLE
Experiment with Socket IO file uploads

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-fileexplorer#131]
There is a socket io file upload module that seems to permit file chunking. This may permit extremely large file uploads over a node app.

https://github.com/vote539/socketio-file-upload

Some experimentation would need to be done to see if this meets our needs. If it works, I see 2 options:
1. Add an upload route as middleware to fileexplorer, or
2. Create a lean standalone node app for processing uploads.

**Comment by ericfranz** [comment]
Won't do. Shouldn't use web-sockets for file upload. There are better solutions to investigate like https://github.com/tus/tusd
