### ISSUE TITLE
Weird file renaming visual glitch

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-fileexplorer#132]
If I rename a file to a directory above it...

![image](https://cloud.githubusercontent.com/assets/4260509/19401854/9ec869d4-922b-11e6-822c-6bfd1c22e865.png)

it will still display in the current directory but with the `../*` notation

![image](https://cloud.githubusercontent.com/assets/4260509/19401872/b75158e4-922b-11e6-8452-3e0ec5b8375a.png)

A page refresh clears the visual glitch.

**Comment by brianmcmichael** [comment]
fixed at https://github.com/OSC/cloudcmd/commit/f40fe0e4563c33c5ca85b76e54b3fb30fb63e410
