### ISSUE TITLE
Add tmp/ to gitignore

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-fileexplorer#133]
When I restart an app, git will complain about unversioned `/tmp` directory.

**Comment by nickjer** [comment]
You could do what Rails does and keep the `/tmp` dir but ignore everything in it...

```
/tmp/*
!/tmp/.keep
```

**Comment by brianmcmichael** [comment]
Done at https://github.com/OSC/ood-fileexplorer/commit/b091bfb71177ef158f4a035f06dc585d8aabba13
