### ISSUE TITLE
Set defaults for apps if not specified

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-fileexplorer#145]
Maybe we should set defaults for these apps if not specified:

https://github.com/OSC/ood-fileexplorer/blob/c62ff6f4e8d0bc8cce0ff7bc14551cdc8e24984d/app.js#L139-L140

something like...

```js
file_editor:            process.env.OOD_FILE_EDITOR || '/pun/sys/file-editor/edit',
shell:                  process.env.OOD_SHELL || '/pun/sys/shell/ssh/default',
```

that way we don't need to copy the `.env.example` over unless the admin wants to override something.

**Comment by brianmcmichael** [comment]
This should be OK, we provide these recommended names for the app folders in their respective install guides.
