### ISSUE TITLE
Directories with long names cause table to be truncated

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-fileexplorer#159]
A portion of my File Explorer appears off screen for directories with long names.

![screenshot from 2017-07-11 10-01-37](https://user-images.githubusercontent.com/4260509/28072160-2ad8dfe4-6620-11e7-9d31-51d782bb023e.png)

There is no horizontal scrollbar to scroll to the other portion. Only solution would be to make my browser window bigger.

**Comment by brianmcmichael** [comment]
This issue is being tracked at https://github.com/OSC/ood-fileexplorer/issues/137

**Comment by ericfranz** [comment]
Closed as duplicate.
