### ISSUE TITLE
Update project for Node.js 4

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-fileexplorer#161]
Our `nodejs010` package is EOL and is superseded by the `rh-nodejs4`

https://www.softwarecollections.org/en/scls/rhscl/rh-nodejs4/

Pending installation of the new collection on the development nodes, the application will need to be re-built and tested with the new version of Node.js, and updated accordingly.

**Comment by brianmcmichael** [comment]
The `rh-nodejs4` package has been installed on `webdev02`

I've tested deployment with the new package and everything worked. There were no warnings during the installation and the app functions as expected.

**Comment by ericfranz** [comment]
So in other words, the app works with both versions of node.js?

**Comment by brianmcmichael** [comment]
Yes. It's throwing warnings with the old version though.

**Comment by MorganRodgers** [comment]
OOD 1.4.x is using `rh-nodejs6`.
