### ISSUE TITLE
Add feature to open HTML files

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-fileexplorer#162]
Ric Anderson from University of Arizona would like to be able to open a selected HTML file within their browser from File Explorer. This could also be extended to handle PDF files.

There was some offline discussion about whether this should be handled with the View button or by adding a new Open button. I say take the simplest approach that can get this pushed out by the 1.1.1 release.

**Comment by nickjer** [comment]
Full context below:

>We have a user here whose applications produce html with pictures.  Right now, they are suffering with firefox over X11 over ssh to view those.  It seems to me the ood file viewer could have an html render (like the view button) that ships the content of a file up the pipe to the browser for display.

**Comment by nickjer** [comment]
This would also resolve #120

**Comment by brianmcmichael** [comment]
Feature added in https://github.com/OSC/ood-fileexplorer/releases/tag/v1.3.6
