### ISSUE TITLE
View Jupyter notebooks

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-fileexplorer#171]
Since we extended the View button for HTML and PDF, another nice addition would be to extend it for Jupyter notebooks.

This is a bit trickier since you will have to call out to an external process but can be done with the [nbconvert](https://github.com/jupyter/nbconvert) tool.

As this requires a python dependency it may be more difficult to wrap it up into the File Explorer app, so I'd hold off on implementing this until maybe File Explorer 2.0.

**Comment by brianmcmichael** [comment]
I'm not sure what you mean by this. For this to happen, we would need to launch a session running Jupyter on the cluster or quick node, then connect the user to that. I don't know that we're at a single-click solution for that yet, as there would be a non-trivial delay while the session launches. 

If you are talking about actually converting the file from one format to another format that is natively supported by the browser, I think that that may be outside of the scope of what a file explorer should do. Where would those files be stored? What would they look like to the user?

The current solutions don't alter or convert the files that are being viewed, we just launch them in a way that they can be rendered natively.

**Comment by ericfranz** [comment]
Right. AFAIK nbconvert will execute every cell in the notebook. If the notebook is doing something like using Jupyter+Spark for a montecarlo simulation, then nbconvert would need to be run in the context of a batch job to produce the desired results to be included.

@nickjer did you imagine something different, such as nbconvert being run without executing the cells? Or maybe in the context of a Jupyter notebook interactive HPC session, there would magically be a button to click to export/share as HTML.

**Comment by nickjer** [comment]
@ericfranz @brianmcmichael 

Sorry about the confusion.

From what I learned in the Jupyter tutorial a Jupyter notebook file (`*.ipynb`) is just a JSON file with inputs and outputs (the solutions of the cells are stored in the JSON file). So I *believe* `nbconvert` doesn't actually *run* the Jupyter notebook file, it will just convert the JSON file into an HTML file for viewing the results in the browser. This is how GitHub is able to easily display Jupyter notebook files.

Note: My interpretation of what `nbconvert` is doing could be wrong though. This could be part of the exploration.

**Comment by MorganRodgers** [comment]
Won't fix.
