### ISSUE TITLE
Directory Copy and Paste issue with Lustre 

### ISSUE THREAD

**Issue by gp4r** [OSC/ood-fileexplorer#190]
Hello,
We are facing an issue with directory copy and paste via File Explorer. It’s working ok with normal NFS share or local folders, but when I copy and paste a folder within Lustre share or from Lustre to other locations. Inside contents are missing.

I have tested from other locations to Lustre share and it worked fine. Any advice would be appreciated.

Thank you

**Comment by ericfranz** [comment]
Related Discourse topic https://discourse.osc.edu/t/directory-copy-and-paste-issue-with-lustre/171

@gp4r See my comment on the Discourse Topic. Let me know if the dependency update fixes your problem. Otherwise will have to look into this more.

**Comment by MorganRodgers** [comment]
Fixed.
