### ISSUE TITLE
Research a good way to debug node apps.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-fileexplorer#57]
I need to come up with a good way to really debug node apps. There isn't an irb-style `console` feature like we have available in Ruby and since we're running passenger as a process I don't have live access to the server-side data or and can't set breakpoints. I can probably set `console.log()` statements and then grep the log files, but that's slow and cumbersome.

The most popular solution seems to be `node-inspector`, but it requires launching a server that you connect to with a Chrome plugin in order to access the server-side variables and I will need to do some experimentation to see if I can get this server running in our environment, but I may need to call in @nickjer for an assist on the server configuration stuff.

I could probably better debug these apps with a "desktop" environment on 'websvcs08' that would allow me to connect to `localhost` with a web browser. 

Other solutions include "Nodeclipse", "Iron Node", and "WebStorm", all of which are also GUI apps.

**Comment by coderaiser** [comment]
You can use one of two options:

- Use undocumented buit-in option [--repl](https://github.com/OSC/cloudcmd/blob/osc-5.3.1/bin/cloudcmd.js#L29) to [open telnet connection](https://github.com/OSC/cloudcmd/blob/osc-5.3.1/lib/server/repl.js).

- Use [node --inspect](http://www.mattzeunert.com/2016/06/01/node-v8-inspector-inspect.html).
