### ISSUE TITLE
Add whitelist of directory roots users are allowed to access

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-fileexplorer#8]
**See below for conversation about whitelist of directories users can access.**

Original issue title:

>### Configure app to use both root and homedir.

Currently, a user starting an app will be directed to their homedir as the root.

This is useful, but they are prevented from going back up the tree to the `gpfs` locations, where they would be able to access their project storage.

There are benefits to having predictable paths, since we will be able to link directly to them and perform REST functions on those paths in other apps, including ruby apps.

You can currently change the root configuration location on the fly with a PATCH request to the API. However, I don't think that this is the best way to go since this setting will persist on the process and paths will no longer be predictable.
API Reference here: https://github.com/cloudcmd/rest

Another option is to configure our `app.js` to route to two separate instances. A GET to "/home" might display a user's homedir as root, while a GET to "/root" might use the "/" path on the filesystem.

Third, we could just have the app serve "/" as root and then attempt to programmatically drop them into their home folder when they link to it from somewhere else. Ex: `./cloudcmd/nfs/08/bmcmichael/`

**Comment by ericfranz** [comment]
If we enforced whitelist at OSC, then we could consider limiting to:

```
/users
/fs/project
/fs/scratch
```

**Comment by nickjer** [comment]
Just wanted to mention that whitelisting directories in the Files App makes me think of the saying:

> A lock only keeps honest people out.

Basically this is very difficult to enforce without possibly using Linux containers or chroot jails.

**Comment by ericfranz** [comment]
The simplest mitigation is in app.js => adding Express middleware to prevent access to any files or directories that are not in a specified whitelist.

This middleware would need to be able to handle all the different types of uris the app accepts that include file paths. Pseudo code below:

```js
app.use(function (req, res, next) {
    var path = (function(req){
        // add code here to parse request and get the path, a file path exists in the URI
    })(req);

    if(! whitelist_paths_contain(path)){
        // of course you would want to provide json or html etc. based on the request's accept header
        res.status(403).send("Not allowed to access");
    }
    else{
        next();
    }
});
```

And `whitelist_paths_contain` could be a simple regex to verify that path is prefix with a string in one of the whitelisted paths, something like this regex (in ruby) `%r{^(/fs/project|/fs/scratch|/users)}` i.e.

```ruby
# paths prevented:
irb(main):009:0> "/etc/httpd/conf/httpd.conf" =~ %r{^(/fs/project|/fs/scratch|/users)}
=> nil
irb(main):010:0> "/" =~ %r{^(/fs/project|/fs/scratch|/users)}
=> nil

# paths in whitelist
irb(main):011:0> "/fs/project/PZS0562" =~ %r{^(/fs/project|/fs/scratch|/users)}
=> 0
irb(main):013:0> "/users/PZS0562/efranz/ondemand/data" =~ %r{^(/fs/project|/fs/scratch|/users)}
=> 0
```

**Comment by MorganRodgers** [comment]
Added in [1.5.0](https://github.com/OSC/ood-fileexplorer/blob/master/CHANGELOG.md#150---2018-12-19).
