### ISSUE TITLE
Copy and Paste button are displaced from each other which can confuse people

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-fileexplorer#87]
The copy button is with the group of buttons that act on the file selection
The paste button is with the group of buttons that act on the current directory (regardless of selection)

This is correct in that you copy a selection and then you paste into the current directory

The ideal solution is to implement https://github.com/AweSim-OSC/osc-fileexplorer/issues/73: display clipboard contents when you "copy". This way the user knows exactly what is happening. Part of this solution may be to enable the paste button only if the user can paste contents; we could also highlight i.e. change the color of the Paste button so that the user knows they can paste the contents (the purple that is the selection might be an option).

So a short term solution here would be:

* A) if there are clipboard contents, enable the paste button; disable by default
* B) hovering over the paste button could show a popover that displays the list of clipboard contents, since this should be available via javascript

In this case, https://github.com/AweSim-OSC/osc-fileexplorer/issues/73 would just be a more complex solution, UI wise.

**Comment by brianmcmichael** [comment]
Fixed by https://github.com/OSC/cloudcmd/pull/30

#73 remains open for advanced features.
